version: "3.4"

services:
  app:
    image: hc2pdf-server
    container_name: hc2pdf-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./.bin:/root/
      - ./templates:/root/templates
